version: '3.8'

services:
  auth:
    build: ./auth
    container_name: simple-auth-service
    restart: always
    environment:
      - PORT=3000
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=https://auth.preventive-tahuna.serveer.biz.id/auth/callback/google
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=https://preventive-tahuna.serveer.biz.id
    networks:
      - preventive-net

  backend:
    build: ./backend
    container_name: api-preventive-tahuna
    restart: always
    # Port 3001 diexpose agar Caddy Host bisa meneruskan trafik (opsional jika lewat frontend)
    ports:
      - "8001:3000" 
    environment:
      - PORT=3000
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=alannuarii
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=db_tahuna
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - preventive-net

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=/api
        - VITE_AUTH_URL=https://loadmonitoring.serveer.biz.id
    container_name: preventive-tahuna
    restart: always
    ports:
      - "3006:3000"
    depends_on:
      - backend
      - auth
    networks:
      - preventive-net

networks:
  preventive-net:
    driver: bridge